# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v4-dependencies-
      - restore_cache:
          keys:
            - v1-docker-{{ .Branch }}-{{ checksum "docker-compose.ci.yml" }}-{{ checksum "docker/Dockerfile" }}
            - v1-docker-
      - run:
          name: Versions
          command: |
            docker --version
            docker-compose --version
            ruby --version
      - run:
          name: Load docker cache
          command: |
            set +o pipefail
            docker load -i ~/caches/images.tar | true
      - run:
          name: Run test
          command: |
            mkdir -p tmp/coverage
            docker-compose -f docker-compose.ci.yml build
            docker-compose -f docker-compose.ci.yml run rspec bin/test
            sudo chown -R circleci:circleci vendor/bundle
      - run:
          name: Save docker cache
          command: |
            mkdir -p ~/caches
            docker save $(docker images -q) -o ~/caches/images.tar
      - save_cache:
          key: v1-docker-{{ .Branch }}-{{ checksum "docker-compose.ci.yml" }}-{{ checksum "docker/Dockerfile" }}
          paths: ~/caches/images.tar
      - save_cache:
          key: v4-dependencies-{{ checksum "Gemfile.lock" }}
          paths: ./vendor/bundle
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage
          destination: coverage
