# https://circleci.com/orbs/registry/orb/circleci/docker
version: 2.1
orbs:
  docker: circleci/docker@0.5.13
jobs:
  test-rails-api:
    executor:
      name: docker/docker
      tag: '3.6'
    working_directory: ~/repo
    steps:
      - checkout
      - docker/install-docker-tools
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "Gemfile.lock" }}
            - v4-dependencies-
      - restore_cache:
          keys:
            - v1-docker-{{ .Branch }}-{{ checksum "docker-compose.ci.yml" }}-{{ checksum "docker/Dockerfile" }}
            - v1-docker-
      - run:
          name: Versions
          command: |
            docker --version
            docker-compose --version
      - run:
          name: Load docker cache
          command: |
            set +o pipefail
            sudo docker load -i ~/caches/images.tar | true
      - run:
          name: Run test
          command: |
            mkdir -p tmp/coverage
            sudo dockerd
            sudo docker-compose -f docker-compose.ci.yml build
            sudo docker-compose -f docker-compose.ci.yml run rspec bin/test
            sudo chown -R circleci:circleci vendor/bundle
      - run:
          name: Save docker cache
          command: |
            mkdir -p ~/caches
            sudo docker save $(docker images -q) -o ~/caches/images.tar
      - save_cache:
          key: v1-docker-{{ .Branch }}-{{ checksum "docker-compose.ci.yml" }}-{{ checksum "docker/Dockerfile" }}
          paths: ~/caches/images.tar
      - save_cache:
          key: v4-dependencies-{{ checksum "Gemfile.lock" }}
          paths: ./vendor/bundle
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage
          destination: coverage
workflows:
  rails-api:
    jobs:
      - test-rails-api
